def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("name", sa.String(length=255), nullable=True))
    op.add_column("users", sa.Column("gender", sa.String(length=20), nullable=True))
    op.add_column("users", sa.Column("age_group", sa.String(length=50), nullable=True))
    op.add_column("users", sa.Column("interests", sa.Text(), nullable=True))
    op.add_column("users", sa.Column("goals", sa.Text(), nullable=True))
    op.add_column("users", sa.Column("bio", sa.Text(), nullable=True))
    op.add_column("users", sa.Column("personality_type", sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "personality_type")
    op.drop_column("users", "bio")
    op.drop_column("users", "goals")
    op.drop_column("users", "interests")
    op.drop_column("users", "age_group")
    op.drop_column("users", "gender")
    op.drop_column("users", "name")
    # ### end Alembic commands ### 