"""Добавлены новые поля настроек: timezone, notification_time, weekly_stats

Revision ID: 0118e9c807fc
Revises: 016c3506fbf6
Create Date: 2025-07-07 23:26:47.793321

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0118e9c807fc"
down_revision: Union[str, None] = "016c3506fbf6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("weekly_stats_enabled", sa.Boolean(), nullable=True)
    )
    op.add_column(
        "users", sa.Column("notification_time", sa.String(length=5), nullable=True)
    )
    op.add_column("users", sa.Column("timezone", sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "timezone")
    op.drop_column("users", "notification_time")
    op.drop_column("users", "weekly_stats_enabled")
    # ### end Alembic commands ###
