"""add_user_profile_fields

Revision ID: 660f1bf1e1ef
Revises: cdf1337f906a
Create Date: 2025-07-04 14:13:02.640156

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "660f1bf1e1ef"
down_revision: Union[str, None] = "cdf1337f906a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("name", sa.String(length=255), nullable=True))
    op.add_column("users", sa.Column("gender", sa.String(length=20), nullable=True))
    op.add_column("users", sa.Column("age_group", sa.String(length=50), nullable=True))
    op.add_column("users", sa.Column("interests", sa.Text(), nullable=True))
    op.add_column("users", sa.Column("goals", sa.Text(), nullable=True))
    op.add_column("users", sa.Column("bio", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "bio")
    op.drop_column("users", "goals")
    op.drop_column("users", "interests")
    op.drop_column("users", "age_group")
    op.drop_column("users", "gender")
    op.drop_column("users", "name")
    # ### end Alembic commands ###
