"""Fix telegram_id field type from Integer to BigInteger

Revision ID: 8f9709de568a
Revises: d5b70f6b7c4f
Create Date: 2025-07-10 23:47:16.804204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8f9709de568a"
down_revision: Union[str, None] = "d5b70f6b7c4f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Change telegram_id column type from Integer to BigInteger
    op.alter_column('users', 'telegram_id', existing_type=sa.INTEGER(), type_=sa.BigInteger(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Revert telegram_id column type from BigInteger to Integer
    op.alter_column('users', 'telegram_id', existing_type=sa.BigInteger(), type_=sa.INTEGER(), nullable=False)
    # ### end Alembic commands ###
