"""update activity_type enum values

Revision ID: af08a2137423
Revises: 7cbb7ea81e38
Create Date: 2025-07-04 20:58:01.958534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "af08a2137423"
down_revision: Union[str, None] = "7cbb7ea81e38"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Update ActivityType enum to match the code definition
    
    # First, create new enum type with all values
    op.execute("CREATE TYPE activitytype_new AS ENUM ('USER_REGISTERED', 'LOGIN', 'ANALYSIS_STARTED', 'ANALYSIS_COMPLETED', 'PROFILE_CREATED', 'PROFILE_UPDATED', 'COMPATIBILITY_TEST', 'SUBSCRIPTION_PURCHASED', 'FEATURE_USED', 'ERROR_OCCURRED', 'LOGOUT')")
    
    # Update the column to use the new enum (with default mapping)
    op.execute("ALTER TABLE user_activities ALTER COLUMN activity_type TYPE activitytype_new USING CASE "
              "WHEN activity_type::text = 'REGISTRATION' THEN 'USER_REGISTERED'::activitytype_new "
              "WHEN activity_type::text = 'ANALYSIS_COMPLETED' THEN 'ANALYSIS_COMPLETED'::activitytype_new "
              "WHEN activity_type::text = 'PROFILE_CREATED' THEN 'PROFILE_CREATED'::activitytype_new "
              "WHEN activity_type::text = 'COMPATIBILITY_TEST' THEN 'COMPATIBILITY_TEST'::activitytype_new "
              "WHEN activity_type::text = 'SUBSCRIPTION_PURCHASED' THEN 'SUBSCRIPTION_PURCHASED'::activitytype_new "
              "WHEN activity_type::text = 'DAILY_CONTENT_VIEWED' THEN 'FEATURE_USED'::activitytype_new "
              "WHEN activity_type::text = 'ACHIEVEMENT_EARNED' THEN 'FEATURE_USED'::activitytype_new "
              "ELSE 'FEATURE_USED'::activitytype_new END")
    
    # Drop old enum and rename new one
    op.execute("DROP TYPE activitytype")
    op.execute("ALTER TYPE activitytype_new RENAME TO activitytype")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Revert back to old enum values
    op.execute("CREATE TYPE activitytype_new AS ENUM ('REGISTRATION', 'ANALYSIS_COMPLETED', 'PROFILE_CREATED', 'COMPATIBILITY_TEST', 'SUBSCRIPTION_PURCHASED', 'DAILY_CONTENT_VIEWED', 'ACHIEVEMENT_EARNED')")
    
    op.execute("ALTER TABLE user_activities ALTER COLUMN activity_type TYPE activitytype_new USING CASE "
              "WHEN activity_type::text = 'USER_REGISTERED' THEN 'REGISTRATION'::activitytype_new "
              "WHEN activity_type::text = 'ANALYSIS_COMPLETED' THEN 'ANALYSIS_COMPLETED'::activitytype_new "
              "WHEN activity_type::text = 'PROFILE_CREATED' THEN 'PROFILE_CREATED'::activitytype_new "
              "WHEN activity_type::text = 'COMPATIBILITY_TEST' THEN 'COMPATIBILITY_TEST'::activitytype_new "
              "WHEN activity_type::text = 'SUBSCRIPTION_PURCHASED' THEN 'SUBSCRIPTION_PURCHASED'::activitytype_new "
              "ELSE 'DAILY_CONTENT_VIEWED'::activitytype_new END")
    
    op.execute("DROP TYPE activitytype")
    op.execute("ALTER TYPE activitytype_new RENAME TO activitytype")
    # ### end Alembic commands ###
