"""fix enum types and constraints for production consistency

Revision ID: b4b252dffe8f
Revises: af08a2137423
Create Date: 2025-07-04 21:01:46.019828

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b4b252dffe8f"
down_revision: Union[str, None] = "af08a2137423"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Convert users.subscription_type from VARCHAR to ENUM
    # First ensure all users have valid subscription types
    op.execute("UPDATE users SET subscription_type = 'FREE' WHERE subscription_type NOT IN ('FREE', 'PREMIUM', 'VIP')")
    
    # Drop default, convert type, restore default
    op.execute("ALTER TABLE users ALTER COLUMN subscription_type DROP DEFAULT")
    op.execute("ALTER TABLE users ALTER COLUMN subscription_type TYPE subscriptiontype USING subscription_type::subscriptiontype")
    op.execute("ALTER TABLE users ALTER COLUMN subscription_type SET DEFAULT 'FREE'")
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Revert subscription_type to VARCHAR
    op.execute("ALTER TABLE users ALTER COLUMN subscription_type DROP DEFAULT")
    op.execute("ALTER TABLE users ALTER COLUMN subscription_type TYPE VARCHAR(20) USING subscription_type::text")
    op.execute("ALTER TABLE users ALTER COLUMN subscription_type SET DEFAULT 'FREE'")
    # ### end Alembic commands ###
