"""Добавлено поле last_profile_edit для ограничения редактирования профиля

Revision ID: d5b70f6b7c4f
Revises: 0118e9c807fc
Create Date: 2025-07-07 23:38:10.466906

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d5b70f6b7c4f"
down_revision: Union[str, None] = "0118e9c807fc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("last_profile_edit", sa.DateTime(timezone=True), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "last_profile_edit")
    # ### end Alembic commands ###
